name: dental-clinic

services:
  database:
    image: mysql:8.0.33
    container_name: dc_database
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    expose:
      - "${DB_PORT}"
    volumes:
      - database:/var/lib/mysql:rw

volumes:
  database:

