// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Gabriela Cecilia Calicanton",
            "url": "http://www.swagger.io/support",
            "email": "gabriela.calicanton@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appointments": {
            "get": {
                "description": "Get all Appointments",
                "tags": [
                    "Appointment"
                ],
                "summary": "Get all Appointments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/AppointmentResponse"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Create a Appointment",
                "tags": [
                    "Appointment"
                ],
                "summary": "Create a Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "AppointmentResponse",
                        "name": "Appointment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AppointmentPost"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/AppointmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/appointments/q": {
            "get": {
                "description": "Get Appointment by DNI",
                "tags": [
                    "Appointment"
                ],
                "summary": "Get Appointment by DNI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient DNI",
                        "name": "dni",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AppointmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/appointments/{id}": {
            "get": {
                "description": "Get Appointment by id",
                "tags": [
                    "Appointment"
                ],
                "summary": "Get Appointment by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AppointmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Update a Appointment",
                "tags": [
                    "Appointment"
                ],
                "summary": "Update a Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AppointmentResponse",
                        "name": "Appointment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AppointmentPut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AppointmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Delete a Appointment",
                "tags": [
                    "Appointment"
                ],
                "summary": "Delete a Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Patch a Appointment",
                "tags": [
                    "Appointment"
                ],
                "summary": "Patch a Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AppointmentResponse",
                        "name": "Appointment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AppointmentPatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AppointmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dentists": {
            "get": {
                "description": "Get all Dentists",
                "tags": [
                    "Dentist"
                ],
                "summary": "Get all Dentists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/DentistResponse"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Create a Dentist",
                "tags": [
                    "Dentist"
                ],
                "summary": "Create a Dentist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "DentistResponse",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DentistPost"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/DentistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dentists/q": {
            "get": {
                "description": "Get Dentist by License",
                "tags": [
                    "Dentist"
                ],
                "summary": "Get Dentist by License",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dentist License",
                        "name": "license",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DentistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dentists/{id}": {
            "get": {
                "description": "Get Dentist by id",
                "tags": [
                    "Dentist"
                ],
                "summary": "Get Dentist by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dentist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DentistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Update a Dentist",
                "tags": [
                    "Dentist"
                ],
                "summary": "Update a Dentist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "DentistResponse",
                        "name": "Dentist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DentistPut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DentistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Delete a Dentist",
                "tags": [
                    "Dentist"
                ],
                "summary": "Delete a Dentist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Dentist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Patch a Dentist",
                "tags": [
                    "Dentist"
                ],
                "summary": "Patch a Dentist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "DentistResponse",
                        "name": "Dentist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DentistPatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DentistResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/patients": {
            "get": {
                "description": "Get all Patients",
                "tags": [
                    "Patient"
                ],
                "summary": "Get all Patients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/PatientResponse"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Create a Patient",
                "tags": [
                    "Patient"
                ],
                "summary": "Create a Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "PatientResponse",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PatientPost"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/PatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/patients/q": {
            "get": {
                "description": "Get Patient by DNI",
                "tags": [
                    "Patient"
                ],
                "summary": "Get Patient by DNI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Patient DNI",
                        "name": "dni",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/patients/{id}": {
            "get": {
                "description": "Get Patient by id",
                "tags": [
                    "Patient"
                ],
                "summary": "Get Patient by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Update a Patient",
                "tags": [
                    "Patient"
                ],
                "summary": "Update a Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatientResponse",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PatientPut"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Delete a Patient",
                "tags": [
                    "Patient"
                ],
                "summary": "Delete a Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "Patch a Patient",
                "tags": [
                    "Patient"
                ],
                "summary": "Patch a Patient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Key",
                        "name": "PUB_KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Patient ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatientResponse",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PatientPatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AppointmentPatch": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "dentist_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "integer"
                }
            }
        },
        "AppointmentPost": {
            "type": "object",
            "required": [
                "date",
                "dentist_license",
                "description",
                "patient_dni"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "dentist_license": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "patient_dni": {
                    "type": "string"
                }
            }
        },
        "AppointmentPut": {
            "type": "object",
            "required": [
                "date",
                "dentist_id",
                "description",
                "patient_id"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "dentist_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "integer"
                }
            }
        },
        "AppointmentResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "dentist_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer"
                }
            }
        },
        "DentistPatch": {
            "type": "object",
            "properties": {
                "last_name": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "DentistPost": {
            "type": "object",
            "required": [
                "last_name",
                "license",
                "name"
            ],
            "properties": {
                "last_name": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "DentistPut": {
            "type": "object",
            "required": [
                "last_name",
                "license",
                "name"
            ],
            "properties": {
                "last_name": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "DentistResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "PatientPatch": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "admission_date": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "PatientPost": {
            "type": "object",
            "required": [
                "address",
                "admission_date",
                "dni",
                "email",
                "last_name",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "admission_date": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "PatientPut": {
            "type": "object",
            "required": [
                "address",
                "admission_date",
                "dni",
                "email",
                "last_name",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "admission_date": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "PatientResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "admission_date": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKey": {
            "description": "Add secret key here",
            "type": "apiKey",
            "name": "SECRET_KEY",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Patient operations for managing Patient",
            "name": "Patient",
            "externalDocs": {
                "description": "Patient operations for managing Patient",
                "url": "http://swagger.io/terms/"
            }
        },
        {
            "description": "Dentist operations for managing Dentist",
            "name": "Dentist",
            "externalDocs": {
                "description": "Dentist operations for managing Dentist",
                "url": "http://swagger.io/terms/"
            }
        },
        {
            "description": "Appointment operations for managing Appointment",
            "name": "Appointment",
            "externalDocs": {
                "description": "Appointment operations for managing Appointment",
                "url": "http://swagger.io/terms/"
            }
        }
    ],
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Dental Clinic API",
	Description:      "API of Dental Clinic",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
